import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Layout} from "antd";
import {Content, Footer, Header} from "antd/lib/layout/layout";
import "antd/dist/reset.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Azurimmo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Layout>
          <Header><h1 className={"text-white"}>Azurimmo</h1></Header>
          <Content className={"p-8 height-full"}>
            {children}
          </Content>
          <Footer>Azurimmo ©2025 Created by Azurimmo</Footer>
      </Layout>
      </body>
    </html>
  );
}
